action: docs, msg: parallel docs
cwd: /scratch/hgv27681/work/epics-containers.github.io
cmd: /venv/bin/python3 /venv/lib/python3.10/site-packages/tox/__main__.py -p
docs recreate: /scratch/hgv27681/work/epics-containers.github.io/.tox/docs
docs installed: accessible-pygments==0.0.3,alabaster==0.7.13,attrs==22.2.0,Babel==2.12.1,beautifulsoup4==4.12.0,black==23.1.0,certifi==2022.12.7,cfgv==3.3.1,charset-normalizer==3.1.0,click==8.1.3,colorama==0.4.6,coverage==7.2.2,distlib==0.3.6,docutils==0.19,-e git+ssh://git@github.com/epics-containers/epics-containers.github.io.git@a6d396ff065d5a1aa8e96aacdcf8736bf9cb6fcf#egg=epics_containers,exceptiongroup==1.1.1,filelock==3.10.0,flake8==6.0.0,flake8-isort==6.0.0,Flake8-pyproject==1.2.3,identify==2.5.21,idna==3.4,imagesize==1.4.1,iniconfig==2.0.0,isort==5.12.0,Jinja2==3.1.2,livereload==2.6.3,MarkupSafe==2.1.2,mccabe==0.7.0,mypy==1.1.1,mypy-extensions==1.0.0,nodeenv==1.7.0,packaging==23.0,pathlib2==2.3.7.post1,pathspec==0.11.1,pipdeptree==2.6.0,platformdirs==3.1.1,pluggy==1.0.0,pre-commit==3.2.0,py==1.11.0,pycodestyle==2.10.0,pydata-sphinx-theme==0.13.1,pyflakes==3.0.1,Pygments==2.14.0,pytest==7.2.2,pytest-cov==4.0.0,PyYAML==6.0,requests==2.28.2,six==1.16.0,snowballstemmer==2.2.0,soupsieve==2.4,Sphinx==5.3.0,sphinx-autobuild==2021.3.14,sphinx-copybutton==0.5.1,sphinx_design==0.3.0,sphinxcontrib-applehelp==1.0.4,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,tomli==2.0.1,tornado==6.2,tox==3.28.0,tox-direct==0.4,types-mock==5.0.0.5,typing_extensions==4.5.0,urllib3==1.26.15,virtualenv==20.21.0
docs run-test-pre: PYTHONHASHSEED='447575357'
docs run-test: commands[0] | sphinx-build -EW --keep-going -T docs build/html
Running Sphinx v5.3.0

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/scratch/hgv27681/work/epics-containers.github.io/docs/conf.py", line 13, in <module>
    import epics_containers
ModuleNotFoundError: No module named 'epics_containers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/venv/lib/python3.10/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/venv/lib/python3.10/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/venv/lib/python3.10/site-packages/sphinx/config.py", line 363, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/scratch/hgv27681/work/epics-containers.github.io/docs/conf.py", line 13, in <module>
    import epics_containers
ModuleNotFoundError: No module named 'epics_containers'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/scratch/hgv27681/work/epics-containers.github.io/docs/conf.py", line 13, in <module>
    import epics_containers
ModuleNotFoundError: No module named 'epics_containers'

ERROR: InvocationError for command /venv/bin/sphinx-build -EW --keep-going -T docs build/html (exited with code 2)
